spring:
  application:
    name: conflict-tracker-api

  datasource:
    url: jdbc:h2:mem:conflicttrackerdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop  # O 'create' para desarrollo
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true  # IMPORTANTE

  sql:
    init:
      mode: always  # Asegura que data.sql se ejecute
      data-locations: classpath:data.sql

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080